version: '3'
services:
  web:  #this container is used host the app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app    
  tests: #this container is solely responsible for rerunning the app if any of the files have changes
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]        